### ISSUE TITLE
Print-out rendering of pre-code shows long gaps

### ISSUE THREAD

**Issue by nitmws** [w3c/tr-design#181]
## Important info

* URL to affected spec: https://w3c.github.io/odrl/profile-bp/
* ReSpec version: 24.30.5
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
The print-out of the web document shows very long empty gaps around the start of a section inside &lt;pre&gt; &lt;/pre&gt; tags, e.g. for examples. This was tested with the browser Chrome 76 and Firefox 68 on a computer with Windows 10 as OS.

But what I was expecting?:
The same as rendered by the browser to the human eye - no big gaps.

Optional, steps to reproduce:
1. Activate the URL to the affected spec in with a Chrome >75 or Firefox >67 on a desktop/laptop Windows 10 computer.
2. Start the print preview - you should see the gaps there already
3. Print out the document.

**Comment by siusin** [comment]
Done and done, @marcoscaceres . I've added you to the [tr-design](https://github.com/orgs/w3c/teams/tr-design) team, who have the write access to that repo. Hope that'd be good enough.

**Comment by marcoscaceres** [comment]
Thanks @siusin! @fantasai, we transferred this over from ReSpec. Details above with a possible fix suggested by @sidvishnoi. Let’s us know what you think!

**Comment by fantasai** [comment]
Thanks @sidvishnoi @nitmws @marcoscaceres ! I swapped out the `page-break-inside: avoid` @sidvishnoi noted as the problem with higher `widows/orphans` values. This allows longer pre blocks to break, while requiring each fragment of it to be at least three lines, to improve context. (This means you need at least six lines in a pre block before we'll allow a break. But more than six lines can break.)

Let me know if this addresses the problem adequately, or if we need to do something similar for the colored boxes as well.

**Comment by marcoscaceres** [comment]
Thanks for the update, @fantasai! Has this been rolled out? I'm still seeing the issue in both Firefox and Chrome... looks good when printing in Safari tho.

**Comment by fantasai** [comment]
@marcoscaceres Seems to have been pushed, and WFM in Firefox with the OP's spec. Can you verify?

**Comment by marcoscaceres** [comment]
Verified, fixed. Thanks @fantasai!
